### ISSUE TITLE
[Question] NVFi dataset making process.

### ISSUE THREAD

**Issue by WongiPark0628** [vLAR-group/NVFi#4]
I wonder how to make an NVFi dataset.

As I know, it is similar to the D-NeRF dataset structure. When I use ColMap to save videos as images, the time information is not 
included in the JSON file. I wonder about how this was included in the JSON file.

I would appreciate it if you tell me how this process.

**Comment by Jinxi-Li** [comment]
Hi, thanks for your interest to our work!

The timestamp here is actually always a prior information when you make your own dataset. For example, if you want to use real-world time of your video, you can just stamp each frame by its frame number over the frame rate. Or you can manually assign a timestamp to each frame based on a normalized time period. 

As for how to include this info in your dataset (if I understand your question right), you don't really need to include this information in your colmap format JSON file. Instead you can assign the timestamps in your dataloader. I believe that's how people usually deal with it. If you want to unify the pipeline and still want to store this timestamp in your data file, you may try to postprocess it into a D-NeRF format.
